name: CI
on:
  pull_request:
    branches: [ master ]
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - name: Install dependencies
        uses: mstksg/get-package@master
        with:
                apt-get: libxml2-utils
      - uses: actions/checkout@v2
      - name: Get fedramp tool
        run: |
          go get -u -v github.com/gocomply/fedramp/cli/gocomply_fedramp
      - name: Convert opencontrol
        run: |
          export PATH="$HOME/go/bin:$PATH"
          make oscal
      - name: Disregard timestamp-only changes
        run: |
          .github/disregard-timestamp-changes.sh
